

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {
int tableno;
String address;
String itemlist[] = {"","","","","","","",""};
int quantity1[] = new int[9];
    
    public Menu() {
        
        
        initComponents();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        aloo = new javax.swing.JCheckBox();
        bindi = new javax.swing.JCheckBox();
        daal = new javax.swing.JCheckBox();
        chana = new javax.swing.JCheckBox();
        rice = new javax.swing.JCheckBox();
        ag2 = new javax.swing.JTextField();
        ag3 = new javax.swing.JTextField();
        ag4 = new javax.swing.JTextField();
        ag1 = new javax.swing.JTextField();
        ag = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fm = new javax.swing.JCheckBox();
        ff = new javax.swing.JCheckBox();
        lf = new javax.swing.JCheckBox();
        ag5 = new javax.swing.JTextField();
        ag6 = new javax.swing.JTextField();
        ag7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zf = new javax.swing.JCheckBox();
        k = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        dk = new javax.swing.JCheckBox();
        ag11 = new javax.swing.JTextField();
        ag10 = new javax.swing.JTextField();
        ag9 = new javax.swing.JTextField();
        ag8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bh = new javax.swing.JCheckBox();
        bm = new javax.swing.JCheckBox();
        bk = new javax.swing.JCheckBox();
        befk = new javax.swing.JCheckBox();
        beefk = new javax.swing.JCheckBox();
        ag17 = new javax.swing.JTextField();
        ag15 = new javax.swing.JTextField();
        ag14 = new javax.swing.JTextField();
        ag13 = new javax.swing.JTextField();
        ag12 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ck = new javax.swing.JCheckBox();
        cf = new javax.swing.JCheckBox();
        cs = new javax.swing.JCheckBox();
        ch = new javax.swing.JCheckBox();
        chh = new javax.swing.JCheckBox();
        ag21 = new javax.swing.JTextField();
        ag20 = new javax.swing.JTextField();
        ag19 = new javax.swing.JTextField();
        ag18 = new javax.swing.JTextField();
        ag16 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mm = new javax.swing.JCheckBox();
        mf = new javax.swing.JCheckBox();
        ma = new javax.swing.JCheckBox();
        mk = new javax.swing.JCheckBox();
        ag25 = new javax.swing.JTextField();
        ag24 = new javax.swing.JTextField();
        ag23 = new javax.swing.JTextField();
        ag22 = new javax.swing.JTextField();
        mg1 = new javax.swing.JCheckBox();
        ag26 = new javax.swing.JTextField();
        buy = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        can = new javax.swing.JButton();
        b = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        tab = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Vegetarian Starters");

        aloo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aloo.setText("Aloo Gobi Rs.100");

        bindi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bindi.setText("Bindi Masala Rs.80");

        daal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        daal.setText("Daal Rs.100");

        chana.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chana.setText("Chana Rs.120");

        rice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rice.setText("Rice Rs.200");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Sea Food");

        fm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fm.setText("Fish Masala Rs.800");

        ff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ff.setText("Fish Fry Rs.700");

        lf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lf.setText("Lahori Fish Masala Rs.1000");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sweet Dishes");

        zf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zf.setText("Zafrani Keer Rs.150");

        k.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        k.setText("Kulfi Rs.100");

        c.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c.setText("Custord Rs.200");

        dk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dk.setText("Diet Kulfi Rs.250");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Non Veg Starters");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Beef");

        bh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bh.setText("Beef Handi Rs.1200");

        bm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bm.setText("Beef Masala Rs.1000");

        bk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bk.setText("Beef Kabab Masala Rs.1400");

        befk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        befk.setText("Beef Boti Kabab Rs.100");

        beefk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        beefk.setText("Beef Karahi Rs.1300");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Chicken");

        ck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ck.setText("Chicken Karahi Rs.700");

        cf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cf.setText("Chicken Fry Rs.500");

        cs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cs.setText("Chicken Sarahadi Rs.1000");

        ch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ch.setText("Chicken Handi Rs.600");

        chh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chh.setText("Chicken Haleem Rs.1000");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mutton");

        mm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mm.setText("Mutton Masala Rs.1500 Per KG");
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });

        mf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mf.setText("Mutton Masala  Rs.1700 Per KG");

        ma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ma.setText("Mutton Afghani Rs.2000 Per KG");

        mk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mk.setText("Mutton Kurma Rs.1600 Per KG");

        mg1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mg1.setText("Mutton Mughlai Rs.1800 Per KG");

        buy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buy.setText("Confrirm Order");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        can.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        can.setText("Cancel");
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Your Bill ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("After Tax");

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Qty");

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Qty");

        tab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tab.setText("Table No");
        tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("OR");

        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Home Delievery");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jTextField2.setText("Enter Address");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c)
                                    .addComponent(dk)
                                    .addComponent(k)
                                    .addComponent(zf)))
                            .addComponent(fm)
                            .addComponent(lf)
                            .addComponent(ff)
                            .addComponent(daal)
                            .addComponent(chana)
                            .addComponent(rice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ag8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aloo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bindi, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ag1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buy)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(106, 106, 106))
                                .addComponent(bk)
                                .addComponent(bm)
                                .addComponent(bh)
                                .addComponent(befk)
                                .addComponent(beefk)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ma)
                                    .addComponent(mk)
                                    .addComponent(mg1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ag25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mf)
                                    .addComponent(mm))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ag22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ag20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cf)
                                        .addComponent(ck)
                                        .addComponent(cs)
                                        .addComponent(ch)
                                        .addComponent(chh))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(ag21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ag19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ag12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bh)
                            .addComponent(ag12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bm)
                            .addComponent(ag13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bk)
                            .addComponent(ag14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ag15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(befk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beefk)
                            .addComponent(ag17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cf)
                            .addComponent(ag16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ck)
                            .addComponent(ag18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cs)
                            .addComponent(ag19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch)
                            .addComponent(ag20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chh)
                            .addComponent(ag21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mm)
                            .addComponent(ag22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mf)
                            .addComponent(ag23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ma)
                            .addComponent(ag24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mg1)
                            .addComponent(ag26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(ag25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tab)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mk)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aloo)
                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bindi)
                    .addComponent(ag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daal)
                    .addComponent(ag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chana)
                    .addComponent(ag3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rice)
                    .addComponent(ag4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lf)
                            .addComponent(ag6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fm)
                            .addComponent(ag7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zf)
                            .addComponent(ag8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(k)
                            .addComponent(ag9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(ag10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ag11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dk)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ag5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ff))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(buy)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(can)
                    .addComponent(add)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    public void checkbox(String name,int quantity){
        try{
         for (int i = 0; i<itemlist.length; i++){
            if (itemlist[i].equals("")){
                itemlist[i] = name;
                quantity1[i] = quantity;
                break;
            }
        }
        }catch(ArrayIndexOutOfBoundsException a){
            a.printStackTrace();
        }
    }
    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed

        int quantity;
        int bill = 0 ;
        if(aloo.isSelected())
        {
            quantity = Integer.parseInt(ag.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=100;
            }
            this.checkbox("Aloo Gobi", quantity);
        }
        if(bindi.isSelected())
        {
            quantity = Integer.parseInt(ag1.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=80;
            }
            this.checkbox("Bindi", quantity);
        }

        if(daal.isSelected())
        {
            quantity = Integer.parseInt(ag2.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=100;
            }
            this.checkbox("Daal", quantity);
        }
        
        if(chana.isSelected())
        {
            quantity = Integer.parseInt(ag3.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=120;
            }
            this.checkbox("Chana", quantity);
        }

        if(rice.isSelected())
        {

            quantity = Integer.parseInt(ag4.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=200;
            }
           this.checkbox("Rice", quantity);
        }

        if(bm.isSelected()) //beef masala
        {
            quantity = Integer.parseInt(ag13.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1000;
            }
            this.checkbox("Beef-Masala", quantity);
        }
        if(bh.isSelected()) // beef handi
        {
            quantity = Integer.parseInt(ag12.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1200;
            }
            this.checkbox("Beef-Handi", quantity);
        }
        if(bk.isSelected()) //beef kabab masala

        {
            quantity = Integer.parseInt(ag14.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1400;
            }
            this.checkbox("Beef-Kabab-Masala", quantity);
        }

        if(befk.isSelected()) //beef boti kabab
        {
            quantity = Integer.parseInt(ag15.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=100;
            }
            this.checkbox("Beef-Boti-Kabab", quantity);
        }

        if(beefk.isSelected()) //beef Karahi
        {
            quantity = Integer.parseInt(ag17.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1300;
            }
            this.checkbox("Beef-Karahi", quantity);
        }

        if(ff.isSelected()) //fish fry
        {
            quantity = Integer.parseInt(ag5.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=700;
            }
            this.checkbox("Fish-Fry", quantity);
        }
        if(lf.isSelected()) //lahori fish
        {
            quantity = Integer.parseInt(ag6.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1000;
            }
            this.checkbox("Lahori-Fish", quantity);
        }
        if(fm.isSelected()) //fish masala
        {
            quantity = Integer.parseInt(ag7.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=800;
            }
            this.checkbox("Fish-Masala", quantity);
        }

        if(zf.isSelected()) //zadfrani keer
        {
            quantity = Integer.parseInt(ag8.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=150;
            }
            this.checkbox("Zafrani-Keer", quantity);
        }
        if(k.isSelected()) //kulfi
        {
            quantity = Integer.parseInt(ag9.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=100;
            }
            this.checkbox("Kulfi", quantity);
        }
        if(c.isSelected()) //custord
        {
            quantity = Integer.parseInt(ag10.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=200;
            }
            this.checkbox("Custord", quantity);
        }
        if(dk.isSelected()) //diet kulfi
        {
            quantity = Integer.parseInt(ag11.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=200;
            }
            this.checkbox("Diet-Kulfi", quantity);
        }

        if(cf.isSelected()) //chicken fry
        {
            quantity = Integer.parseInt(ag16.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=500;
            }
            this.checkbox("Chicken-Fry", quantity);
        }
        
        if(ck.isSelected()) //chicken karahi
        {
            quantity = Integer.parseInt(ag18.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=700;
            }
            this.checkbox("Chicken-Karahi", quantity);
        }
        if(cs.isSelected()) //chicken sarhadi
        {
            quantity = Integer.parseInt(ag19.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1000;
            }
            this.checkbox("Chicken-Sarhadi", quantity);
        }

        if(ch.isSelected())  //chicken handi
        {

            quantity = Integer.parseInt(ag20.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=600;
            }
            this.checkbox("Chicken-Handi", quantity);
        }

        if(chh.isSelected()) //chicken haleem
        {
            quantity = Integer.parseInt(ag21.getText());
            for(int i = 0 ; i < quantity ; i++)
            {
                bill +=1000;
            }
            this.checkbox("Chicken-Haleem", quantity);
        }

         if(mm.isSelected()) //mutton masala
	{
	 quantity = Integer.parseInt(ag22.getText()); 
            for(int i = 0 ; i < quantity ; i++)
            {
		   bill +=1500;
             }
            this.checkbox("Mutton-Masala", quantity);             
		  }
		 if(mf.isSelected()) //mutton fry
		     {
			        	 quantity = Integer.parseInt(ag23.getText()); 
				           for(int i = 0 ; i < quantity ; i++)
				           {
				               bill +=1700;
				           }
                                           this.checkbox("Mutton-Fry", quantity);
			           
			         }
			         if(ma.isSelected()) //mutton afghani
			         {
			        	 quantity = Integer.parseInt(ag24.getText()); 
				           for(int i = 0 ; i < quantity ; i++)
				           {
				               bill +=2000;
				           }
                                           this.checkbox("Mutton-Afghani", quantity);
			         }
			             
			         if(mg1.isSelected()) //mutton muglai
			         {
			        	 quantity = Integer.parseInt(ag26.getText()); 
				           for(int i = 0 ; i < quantity ; i++)
				           {
				               bill +=1800;
				           }
                                           this.checkbox("Mutton-Muglai", quantity);
			         }
			         if(mk.isSelected()) //mutton kurma
			         {
			        	 quantity = Integer.parseInt(ag25.getText()); 
				           for(int i = 0 ; i < quantity ; i++)
				           {
				               bill +=1600;
				           }
                                           this.checkbox("Mutton-Kurma", quantity);
			         }
          
          int tax = 0;
          tax = bill * 10 / 100;
        b1.setText(Integer.toString(bill));
        
         bill = bill + tax;
         
         
        b.setText(Integer.toString(bill));
        if(tab.isSelected())
         {
               tableno = Integer.parseInt(jTextField1.getText());
               this.address = "no address";
         }else{
            tableno = -1;
            this.address = jTextField2.getText();
        }
        connectiondb connectdb = new connectiondb();
        connectdb.connection(itemlist[0], quantity1[0], itemlist[1], quantity1[1], itemlist[2], quantity1[2], itemlist[3], quantity1[3], itemlist[4], 
                quantity1[4], itemlist[5], quantity1[5], itemlist[6], quantity1[6], itemlist[7], quantity1[7], tableno, bill, tax, this.address);
        
    }//GEN-LAST:event_buyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Clear Button
        rice.setSelected(false);
        beefk.setSelected(false);
        befk.setSelected(false);
        mg1.setSelected(false);
        fm.setSelected(false);
        bh.setSelected(false);
        chh.setSelected(false);
        ch.setSelected(false);
        cs.setSelected(false);
        ck.setSelected(false);
        cf.setSelected(false);
        dk.setSelected(false);
        c.setSelected(false);
        k.setSelected(false);
        ch.setSelected(false);
        chh.setSelected(false);
        mk.setSelected(false);
        mk.setSelected(false);
        ma.setSelected(false);
        mf.setSelected(false);
        mm.setSelected(false);
        lf.setSelected(false);
        ff.setSelected(false);
        bk.setSelected(false);
        bm.setSelected(false);
        chana.setSelected(false);
        daal.setSelected(false);
        bindi.setSelected(false);
        aloo.setSelected(false);
        zf.setSelected(false);
        ff.setSelected(false);
        b1.setText("  ");
        b.setText( "  ");
        ag.setText(" ");
        ag1.setText(" ");
        ag2.setText(" ");
        ag3.setText(" ");
        ag4.setText(" ");
        ag5.setText(" ");
        ag6.setText(" ");
        ag7.setText(" ");
        ag8.setText(" ");
        ag9.setText(" ");
        ag10.setText(" ");
        ag11.setText(" ");
        ag12.setText(" ");
        ag13.setText(" ");
        ag14.setText(" ");
        ag15.setText(" ");
        ag16.setText(" ");
        ag17.setText(" ");
        ag18.setText(" ");
        ag19.setText(" ");
        ag20.setText(" ");
        ag21.setText(" ");
        ag22.setText(" ");
        ag23.setText(" ");
        ag24.setText(" ");
        ag25.setText(" ");
        ag26.setText(" ");
                    
                    
                
            
          
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        System.exit(0);
    }//GEN-LAST:event_canActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabActionPerformed
     
         if(tab.isSelected())
         {
               add.setSelected(false);
         }
      
    }//GEN-LAST:event_tabActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
         if(add.isSelected())
      {
          tab.setSelected(false);
      }
    }//GEN-LAST:event_addActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton add;
    private javax.swing.JTextField ag;
    private javax.swing.JTextField ag1;
    private javax.swing.JTextField ag10;
    private javax.swing.JTextField ag11;
    private javax.swing.JTextField ag12;
    private javax.swing.JTextField ag13;
    private javax.swing.JTextField ag14;
    private javax.swing.JTextField ag15;
    private javax.swing.JTextField ag16;
    private javax.swing.JTextField ag17;
    private javax.swing.JTextField ag18;
    private javax.swing.JTextField ag19;
    private javax.swing.JTextField ag2;
    private javax.swing.JTextField ag20;
    private javax.swing.JTextField ag21;
    private javax.swing.JTextField ag22;
    private javax.swing.JTextField ag23;
    private javax.swing.JTextField ag24;
    private javax.swing.JTextField ag25;
    private javax.swing.JTextField ag26;
    private javax.swing.JTextField ag3;
    private javax.swing.JTextField ag4;
    private javax.swing.JTextField ag5;
    private javax.swing.JTextField ag6;
    private javax.swing.JTextField ag7;
    private javax.swing.JTextField ag8;
    private javax.swing.JTextField ag9;
    private javax.swing.JCheckBox aloo;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private javax.swing.JCheckBox beefk;
    private javax.swing.JCheckBox befk;
    private javax.swing.JCheckBox bh;
    private javax.swing.JCheckBox bindi;
    private javax.swing.JCheckBox bk;
    private javax.swing.JCheckBox bm;
    private javax.swing.JButton buy;
    private javax.swing.JCheckBox c;
    private javax.swing.JButton can;
    private javax.swing.JCheckBox cf;
    private javax.swing.JCheckBox ch;
    private javax.swing.JCheckBox chana;
    private javax.swing.JCheckBox chh;
    private javax.swing.JCheckBox ck;
    private javax.swing.JCheckBox cs;
    private javax.swing.JCheckBox daal;
    private javax.swing.JCheckBox dk;
    private javax.swing.JCheckBox ff;
    private javax.swing.JCheckBox fm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox k;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JCheckBox lf;
    private javax.swing.JCheckBox ma;
    private javax.swing.JCheckBox mf;
    private javax.swing.JCheckBox mg1;
    private javax.swing.JCheckBox mk;
    private javax.swing.JCheckBox mm;
    private javax.swing.JCheckBox rice;
    private javax.swing.JRadioButton tab;
    private javax.swing.JCheckBox zf;
    // End of variables declaration//GEN-END:variables
}
